### ISSUE TITLE
Early Spring 2023 Event Map support

### ISSUE THREAD

**Issue by blahaj-blast** [XVs32/kcauto_custom#20]
Attempting to add support for current event maps starting with E2 (farming for for drops) currently stuck with this error upon sortie start (at the LBAS node select screen, but likely happens without LBAS)

`[94m[2023-03-12 00:01:40] Starting sortie.←[0m
Traceback (most recent call last):
  File "C:\Users\Render Box\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Render Box\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kcauto\__main__.py", line 19, in <module>
    kcauto_main()
  File "kcauto\kcauto_wrapper.py", line 37, in kcauto_main
    _.kcauto.run_combat_logic()
  File "kcauto\kcauto.py", line 224, in run_combat_logic
    if com.combat.conduct_sortie():
  File "kcauto\combat\combat_core.py", line 225, in conduct_sortie
    return self._conduct_sortie(cfg.config.combat.sortie_map)
  File "kcauto\combat\combat_core.py", line 248, in _conduct_sortie
    self._handle_combat(sortie_map)
  File "kcauto\combat\combat_core.py", line 328, in _handle_combat
    self._find_next_node(result[KCSAPIEnum.SORTIE_START.name][0])
  File "kcauto\combat\combat_core.py", line 730, in _find_next_node
    next_node = self._get_next_node_from_edge(edge)
  File "kcauto\combat\combat_core.py", line 737, in _get_next_node_from_edge
    return self.map_data.edges[edge][1]
KeyError: 38`

Unsure of next steps, currently trying to update existing E-2.json

**Comment by XVs32** [comment]
Hi blahaj, 

The event map in current kcauto_custom is made for old event in 2022,
it does need a update to work for 2023 spring event.

`KeyError: 38` shows that you start from node `2` and navigating to node `M`.
You didn't provide further info but I believe it is where your fleet going?

After all, both `nodes` and `edges` in `​E-X.json` needs update.
You could wait for my update or make your own `​E-2.json` update.

Btw I recommend you to take a look into [KC3 source code](https://github.com/KC3Kai/KC3Kai/blob/master/src/data/edges.json) if you are going to make the map update yourself.

**Comment by blahaj-blast** [comment]
Yeah that's what it was trying to do, I had started to get the nodes and edges updated.
I wasn't quite sure if the error might have been because start 2 is under the LBAS screen at the start and I saw the nodes defined, but not the start locations.

**Comment by blahaj-blast** [comment]
Okay, I copied the edges from the KC3 page and it didn't crash, but now it just can't find the right node. Is there anywhere the X/Y exist already? I used to have an extension to find them but it seems to be gone.

**Comment by XVs32** [comment]
As far as I know there is no website that provide the X/Y coordinate for the nodes.
Personally I made a tool in `./tool/get_mouse_location.py`

You click top left of the map, then click from A to Z, it will show you the X/Y coordinate then you can copy(and edit) the result.

**Comment by blahaj-blast** [comment]
Alright cool, I'll look into that. If I get E2 up and working I'll be sure to share.
