### ISSUE TITLE
Can't find reference point

### ISSUE THREAD

**Issue by Kaboom0234** [XVs32/kcauto_custom#29]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): Linux v1.0.0_pre-release
* Operating system and/or VM: VMWare running Ubuntu. Browser is Chromium

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: Every time I try to launch

#### Issue

Please provide a thorough description of the issue. Screenshots, videos, or at least a step-by-step description of what is happening in the game is typically necessary to debug.

Everything is freshly unzipped, unchanged in any way. Launch the basic version with ./kcauto_cui, arrow over to the panel, reload config to launch, and it fails. KC3 Customizations are off, 127.0.0.1:9222 shows as a blank page.

#### Log
```
[insert ~50 lines of console log (or more) here; remove section if irrelevant]
```

                      File "util/kca.py", line 412, in find
       active         File "pyvisauto/__init__.py", line 115, in find
                    pyvisauto.FindFailed: assets/global/dmm_logo.png not found i
                    n [ X:0, Y:0, W:1920, H:1080 ]!
                    
                    During handling of the above exception, another exception oc
       disable      curred:
       disable      
                    Traceback (most recent call last):
                      File "startup/kcauto_wrapper.py", line 21, in kcauto_main 
                      File "startup/kcauto.py", line 37, in find_dmm
                      File "util/kca.py", line 147, in find_dmm
                    pyvisauto.FindFailed
                    
        02:00       [2023-05-08 00:28:50] End stacktrace.
         15         [2023-05-08 00:28:50] Attempting recovery.
                    [2023-05-08 00:28:50] Finding kancolle.
                    [2023-05-08 00:28:57] Could not find Kancolle reference poin
                    t.
                    [2023-05-08 00:28:58] Recovery failed. Shutting down kcauto.
                    
       disable      kcauto ended

#### Config
```
[insert relevant config sections here; remove section if irrelevant]
```

(First thing first, thanks for the screenshot. 
Good thing you did censor your id, though it could still be dangerous since there are still quite a lot of info in the screenshot, that's why I removed the screenshot for now
-- XVs32)

**Comment by XVs32** [comment]
Hi Kaboom,

I did compare your screenshot to the assets in kcauto_custom and I don't see any difference between this two, so I don't think this is a zooming problem.
![image](https://user-images.githubusercontent.com/16824564/236819378-494ed757-5640-4c89-9b50-49df696dfb21.png)

The next thing I would suspect is the screen setup,   
is your screen a 1920*1080 setup? Or it is a dual screen setup and somehow kcauto_custom is only searching [0, 0, 1920, 1080] area? (Although it works fine in my ubuntu dual screen setup.. so...)

Btw, I believe your kcauto_custom will still break even if it manage to find the dmm logo,  
since your dmm logo is not located all the way to the top left corner (which is not your fault, I will have to find a way to fix this).  
In the mean time, changing the interaction setting in `./configs/config_cui.json`to `direct_control` should help.
```"general.interaction_mode": "direct_control"```

XVs32

**Comment by Kaboom0234** [comment]
Thanks for removing the screenshot.

1920x1080(16:9). It is only on a single screen. I managed to get the top notch removed to see if that would help as well as running it in full screen but to no avail. Tried swapping the logo picture it was using as reference as well to a different grab of the DMM logo as well as the icon on the tab to see if that could help.

![image](https://user-images.githubusercontent.com/85782536/236871995-7fc8327d-7fd3-4f6b-a547-3a698b152313.png)

It may be unrelated but the terminal for the devport chromium appears to be throwing some errors.

![image](https://user-images.githubusercontent.com/85782536/236872546-9a6b959b-03f7-435a-979d-fa46baec832b.png)

Hopefully I did better with not having any potentially damaging things in the screenshots this time.

**Comment by XVs32** [comment]
Hi Kaboom,

To be honest I have no idea why is this happening at the moment (maybe there is something wrong with the screen capturing),
I will have to build my own VM env and try to reproduce the problem.

Or maybe I will provide you my VM if I could successfully run kcauto_custom in it.

PS: Good work on the screenshot this time(thumbs up)
