### ISSUE TITLE
Automatic Monthly Clears

### ISSUE THREAD

**Issue by blahaj-blast** [XVs32/kcauto_custom#31]
It would be nice to be able to have auto mode also do monthly map clears like they do quests and check that they are clear. It would be nice if this option was also able to be prioritized over quests, though I imagine anyone wanting to set this option would want that to be the case.

Though I guess _which_ ones run should be a config as some may not find 5-5 worth doing and idk how 6-5 LBAS would work with auto mode.

**Comment by XVs32** [comment]
Good idea, a milestone is set here

https://github.com/XVs32/kcauto_custom/milestone/2
