### ISSUE TITLE
expedition issue

### ISSUE THREAD

**Issue by sharvies** [XVs32/kcauto_custom#32]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 1.0.0 windows
* Operating system and/or VM: windows 10

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: consistent

#### Issue
before i say, i am sorry for my poor english because i am not english speaker. so i want to go to A2 on expedition, but it doesn't work. i set the expedition file to [101],[20],[41] for shinden quest. but in first expedition screen, it stops. how can i solve this problem?

#### Log
```
[insert ~50 lines of console log (or more) here; remove section if irrelevant]
```
![log](https://github.com/XVs32/kcauto_custom/assets/130654452/204c4cf1-9821-4c9e-98ec-2a649864da54)

#### Config
```
[insert relevant config sections here; remove section if irrelevant]
```
{
    "combat.check_fatigue": true,
    "combat.check_lbas_fatigue": false,
    "combat.clear_stop": false,
    "combat.enabled": false,
    "combat.fleet_mode": "standard",
    "combat.fleet_presets": [],
    "combat.lbas_group_1_nodes": [],
    "combat.lbas_group_2_nodes": [],
    "combat.lbas_group_3_nodes": [],
    "combat.lbas_groups": [],
    "combat.node_formations": [],
    "combat.node_night_battles": [],
    "combat.node_selects": [],
    "combat.port_check": false,
    "combat.push_nodes": [],
    "combat.repair_limit": 3,
    "combat.repair_timelimit_hours": 1,
    "combat.repair_timelimit_minutes": 0,
    "combat.reserve_repair_dock": true,
    "combat.retreat_limit": 4,
    "combat.retreat_points": [],
    "combat.sortie_map": "1-1",
    "event_reset.enabled": true,
    "event_reset.farm_difficulty": 2,
    "event_reset.frequency": 3,
    "event_reset.reset_difficulty": 3,
    "expedition.enabled": true,
    "expedition.fleet_2": [
        101
    ],
    "expedition.fleet_3": [
        20
    ],
    "expedition.fleet_4": [
        41
    ],
    "factory.build_recipe": [
        30,
        30,
        30,
        30
    ],
    "factory.develop_recipe": [
        10,
        10,
        10,
        10
    ],
    "factory.enabled": false,
    "general.chrome_dev_port": 9222,
    "general.interaction_mode": "chrome_driver",
    "general.jst_offset": 0,
    "general.paused": false,
    "passive_repair.enabled": true,
    "passive_repair.repair_threshold": 1,
    "passive_repair.slots_to_reserve": 2,
    "pvp.enabled": true,
    "pvp.fleet_preset": 1,
    "quest.enabled": false,
    "quest.quests": [
        "Bd1",
        "Bd2",
        "Bd3",
        "Bd4",
        "Bd5",
        "Bd6",
        "Bd7",
        "Bd8",
        "Bw1",
        "Bw2",
        "Bw3",
        "Bw4",
        "Bw5",
        "Bw7",
        "Bw8",
        "Bw9",
        "Bw10",
        "Bm2",
        "Bm3",
        "Bm4",
        "Bm5",
        "Bm6",
        "Bm8",
        "Bq1",
        "Bq3",
        "Bq4",
        "Bq8",
        "Bq9",
        "Bq10",
        "Bq11",
        "Bq12",
        "C2",
        "C3",
        "C4",
        "C8",
        "C16",
        "C29",
        "D2",
        "D3",
        "D4",
        "D9",
        "D11",
        "D22",
        "D24",
        "E3",
        "E4",
        "F5",
        "F6",
        "F7",
        "F8"
    ],
    "scheduler.enabled": false,
    "scheduler.rules": [
        "time:0000:stop:kcauto",
        "sorties_run:0:stop:combat"
    ],
    "ship_switcher.enabled": false,
    "ship_switcher.slots": {}
}

**Comment by XVs32** [comment]
[Solved by user](https://discord.com/channels/370233436327247872/370234082778546176/1112287055830073344).

```
sharvies — 05/28/2023 3:51 PM
i found it. it was problem of pixel
i used kcauto in my laptop that has 1366x768. kcauto cli version worked in my laptop. but recent windows version doesn't work in that resolution. in my labtop the screen is slightly short because of the DMM GAMES Logo in top left of screen.
it works in my desktop that has 1920x1080 properly
```
