### ISSUE TITLE
Expedition IDs

### ISSUE THREAD

**Issue by Danielosama** [XVs32/kcauto_custom#60]
I am trying out your fork with a config for 3-2 ammo farming + expeditions, but I run into the following error:

![image](https://github.com/XVs32/kcauto_custom/assets/12687427/35a1e0af-ebc7-4c71-bd9e-7dd7a63622b0)

Is there a list of Expedition IDs? I thought the ID of the expedition A2 was "101", but appaerently something is wrong.

All best,

**Comment by XVs32** [comment]
Hello [Danielosama](https://github.com/Danielosama),

After a quick debug, apparently this is a mistake I've made recently.
I will fix this in the next coming version.

In the mean time, if you are running kcauto_costom from source code(not using .exe),
changing line 125 in `expedition/expedition_core.py`
from 
```
self.exp_rank.append({"id":int(id.expedition), "score":0})
```
to
```
self.exp_rank.append({"id":int(id.value), "score":0})
```
should solve the problem.

Thank you for your report.

Sincerely,
XVs32

**Comment by Danielosama** [comment]
That fixed it, thanks.
