### ISSUE TITLE
Windows version clicking too fast

### ISSUE THREAD

**Issue by XVs32** [XVs32/kcauto_custom#66]
#### What

* Delay between click and mouse move is not enough in Windows 

#### How

* `sleep()` might broken in Windows, find the reason why. Or
* increase the delay in Windows

#### Result

* Where is the product now

#### Reference

* url, pdf, ppt etc.

**Comment by kevin01523** [comment]
i experience this.i use direct control to somewhat lessen the instance this occurs instead of chrome driver

**Comment by XVs32** [comment]
Now the sleep in both chrome driver and direct control are forced to util.sleep version (in babe27b7401abd08d37c5ee746c521525e91d29c)
Direct control in Windows is tested and doing well.
Chrome driver, however, is not getting the correct init coor, fix will be done in  https://github.com/XVs32/kcauto_custom/issues/81
