### ISSUE TITLE
Program will crash during startup, failing to find a reference point 

### ISSUE THREAD

**Issue by Gbraker7000** [XVs32/kcauto_custom#68]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`):

V2.0.0

* Operating system and/or VM:

Running a VM with ubuntu 22.04.3 LTS

#### Issue variability
The issue is consistent, it will happen without fail.

#### Issue
During when reloading the config of Kcauto_cui, you get the following error

https://i.imgur.com/5LybouJ.png

For reference this is what my screen looks like

https://i.imgur.com/mdKZ2A8.jpeg

#### Config

I'm using the default config

**Comment by XVs32** [comment]
Hi [Gbraker7000](https://github.com/Gbraker7000),

Ubuntu 22.04 switched to Wayland and the new windowing system doesn't work well with PyAutoGUI.
Switching back to the good old X11 should fix the problem

https://www.reddit.com/r/linuxquestions/comments/10dkaxz/linux_screenshots_return_black_screens/

Wayland return a black screen:
![image](https://github.com/XVs32/kcauto_custom/assets/16824564/2946dc3e-8cd4-41a2-858e-a0ef50b60483)

X11 works well:
![image](https://github.com/XVs32/kcauto_custom/assets/16824564/770470bc-c374-4341-ae5b-b25b44a77044)


Sincerely,
XVs32
